CREATE TABLE IF NOT EXISTS webring (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS webring_members (
  webring_id INTEGER NOT NULL,
  member_id INTEGER  PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  FOREIGN KEY(webring_id) REFERENCES webring(id) ON DELETE CASCADE
);

